### ISSUE TITLE
Request validation error - Element 'T=DepartmentKey' is abstract and cannot be used in an instance.

### ISSUE THREAD

**Issue by CatalyticMusa** [nigelm/broadworks_ocip#10]
* Broadworks OCI-P Interface version: 2.0.1
* Python version: 3.9.1
* Operating System: MacOS Catalina

### Description

I am creating a "bulk task" application for internal use at our company. I have successfully been able to create groups, departments and users independently.

However, I would preferably like to assign a user to a department upon creation of the user. The API 'UserAddRequest' commands (all of them) require the department to be of type OCI.department (which I could only backtrace to be of type DepartmentKey).

Problem is, when I instantiate DepartmentKey, I receive the following error: 

OCIErrorResponse(None: [Error 6004] OCI XML Request validation error - Element 'T=DepartmentKey' is abstract and cannot be used in an instance.

I understand that the error means it won't instantiate an abstract class, but the command seemingly won't accept any other type (I.E. GroupDepartmentKey /  EnterpriseDepartmentKey)? I believe this could be a bug in the code but If not, please could you assist in helping me resolve this issue. 

The same is true for commands like 'UserModifyRequest', which is used in the examples below:

####################################################################
Using DepartmentKey "instance"
####################################################################

COMMAND:
resp = api.command(
    "UserModifyRequest16",
    user_id="test-test@sip.test.com", #removed actual domain
    department=DepartmentKey()
)

print(resp)

```
Traceback (most recent call last):
  File "/Users/Musa/Desktop/2022 Projects/Python/ocip-testing/test.py", line 43, in <module>
    resp = api.command(
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/api.py", line 370, in command
    return self.receive_response()
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/api.py", line 259, in receive_response
    return self.decode_xml(content)
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/api.py", line 289, in decode_xml
    result.post_xml_decode_()
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/base.py", line 578, in post_xml_decode_
    raise OCIErrorResponse(
broadworks_ocip.exceptions.OCIErrorResponse: OCIErrorResponse(None: [Error 6004] OCI XML Request validation error - Element 'T=DepartmentKey' is abstract and cannot be used in an instance
<department xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/>
)


####################################################################
Using GroupDepartmentKey instance
####################################################################


Traceback (most recent call last):
  File "/Users/Musa/Desktop/2022 Projects/Python/ocip-testing/test.py", line 36, in <module>
    resp = api.command(
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/api.py", line 369, in command
    self.send_command(command, **kwargs)
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/api.py", line 225, in send_command
    xml = self.get_command_xml(command, **kwargs)
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/api.py", line 207, in get_command_xml
    cmd = self.get_command_object(command, **kwargs)
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/api.py", line 190, in get_command_object
    cmd = cls(session_id=self.session_id, **kwargs)
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/base.py", line 422, in __init__
    super().__init__(**kwargs)
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/base.py", line 85, in __init__
    raise TypeError(
TypeError: UserModifyRequest16: Expected department to be type <class 'broadworks_ocip.types.DepartmentKey'> but it is <class 'broadworks_ocip.types.GroupDepartmentKey'>


####################################################################
Using DepartmentKey class, not instance of
####################################################################

SyntaxError: invalid syntax
Musas-MacBook-Pro:ocip-testing Musa$ poetry run python3 test.py
Traceback (most recent call last):
  File "/Users/Musa/Desktop/2022 Projects/Python/ocip-testing/test.py", line 36, in <module>
    resp = api.command(
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/api.py", line 369, in command
    self.send_command(command, **kwargs)
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/api.py", line 225, in send_command
    xml = self.get_command_xml(command, **kwargs)
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/api.py", line 207, in get_command_xml
    cmd = self.get_command_object(command, **kwargs)
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/api.py", line 190, in get_command_object
    cmd = cls(session_id=self.session_id, **kwargs)
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/base.py", line 422, in __init__
    super().__init__(**kwargs)
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/base.py", line 85, in __init__
    raise TypeError(
TypeError: UserModifyRequest16: Expected department to be type <class 'broadworks_ocip.types.DepartmentKey'> but it is <class 'type'>

**Comment by CatalyticMusa** [comment]
Hi Nigel,

As mentioned in my original issue, it does not accept `GroupDepartmentKey` or `EnterpriseDepartmentKey`. 

Is there a workaround I can use to get that functionality working?

**Comment by nigelm** [comment]
I've disabled the type checking and pushed out an updated release (version 2.0.2), so that should now work but has fewer checks that your type combinations are sane.

I'll look at getting the type checking working for this type of object.

**Comment by CatalyticMusa** [comment]
Thanks for the fixing, I tested on my end using the following code:

```
api = BroadworksAPI(
    host="host.domain.com", 
    port=2208,
    username="UserName", 
    password="NotARealPassword1!"
)

group_key = GroupDepartmentKey(
        service_provider_id="NotARealISP Telecomunications",
        group_id="TEST001",
        name="TEST Department",    
    )

resp = api.command(
    "UserModifyRequest16",
    user_id="test-test@sip.notarealisp.com",
    department=group_key
)

print(resp)
```

I got the following error:

```
Traceback (most recent call last):
  File "/Users/Musa/Desktop/2022 Projects/Python/ocip-testing/test.py", line 42, in <module>
    resp = api.command(
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/api.py", line 370, in command
    return self.receive_response()
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/api.py", line 259, in receive_response
    return self.decode_xml(content)
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/api.py", line 289, in decode_xml
    result.post_xml_decode_()
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/base.py", line 578, in post_xml_decode_
    raise OCIErrorResponse(
broadworks_ocip.exceptions.OCIErrorResponse: OCIErrorResponse(None: [Error 6004] OCI XML Request validation error - Element 'T=DepartmentKey' is abstract and cannot be used in an instance
```

It's now realising that the `GroupDepartmentKey` is purely `DepartmentKey`?

**Comment by nigelm** [comment]
OK it looks like I had missed that `DepartmentKey` ( and `SortCriteria`, possibly some others) are flagged as `abstract` types.

That needs some additional work on the code that emits XML (and likely some additional work on the schema parsing etc).

I'll have a think about that - for now have dropped a failing test into the new branch https://github.com/nigelm/broadworks_ocip/tree/abstract_types

If you are able to do this operation through the normal UI, and get a command trace through Broadworks (I haven't worked with that side of things so cannot say exactly how thats done), I would really appreciate a copy of the trace (obviously change user ids and anything else potentially sensitive to anonymised values).  I really could do with seeing the XML tags and structure for the command.

**Comment by nigelm** [comment]
There is a hopefully working version in the `abstract_types` branch - see https://github.com/nigelm/broadworks_ocip/tree/abstract_types

I do not have a live environment I can test this on currently - we do not use departments - and will need to discuss with the system managers before I attempt to test this even on a development system.  So I have put this up to see if someone else can test it out for me.

If it fails I need the Broadworks error message or even better the debug trace for the failing command (feel free to elide session ids or private data).

**Comment by CatalyticMusa** [comment]
Thanks for that, I will test this out sometime this week, I have a service provider level environment I can test this on. Once done, I will let you know.

**Comment by CatalyticMusa** [comment]
**Request Sent:**

```
g = GroupDepartmentKey(
        service_provider_id="Fake Telecommunications",
        group_id="AJTST",
        name="HQ",    
)

resp = api.command(
    "UserAddRequest14", 
    service_provider_id="Fake Telecommunications", 
    group_id="AJTST", 
    user_id="fakeuser@sip.faketelecommunications.com", 
    password="goodflavor!1",
    first_name="Fake", 
    last_name="User",
    calling_line_id_first_name="Fake",
    calling_line_id_last_name="User",
    email_address="Fakeuser@fakeemail.com",
    phone_number="27871231234",
    department=g,
    extension="1234",
)
```

**Response Received:**

```
Traceback (most recent call last):
  File "/Users/Musa/Desktop/2022 Projects/Python/ocip-testing/test.py", line 20, in <module>
    resp = api.command(
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/api.py", line 370, in command
    return self.receive_response()
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/api.py", line 259, in receive_response
    return self.decode_xml(content)
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/api.py", line 289, in decode_xml
    result.post_xml_decode_()
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/base.py", line 605, in post_xml_decode_
    raise OCIErrorResponse(
broadworks_ocip.exceptions.OCIErrorResponse: OCIErrorResponse(None: [Error 6004] OCI XML Request validation error - Expected elements 'department language timeZone alias accessDeviceEndpoint trunkGroupDeviceEndpoint title pagerPhoneNumber mobilePhoneNumber emailAddress yahooId addressLocation address' instead of 'groupDepartmentKey' here in element command
<groupDepartmentKey xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><serviceProviderId>Fake Telecommunications</serviceProviderId><groupId>AJTST</groupId><name>HQ</name></groupDepartmentKey>

```


Removing the post_xml decode function just returns an error response with the same message in it. Does not seem to work.

**Comment by nigelm** [comment]
So it looks like the abstract types - ie the variations of DepartmentKey - just put their contents into the object without an extra layer of container - see https://github.com/nigelm/broadworks_ocip/commit/63f1454ec448660145f2c012185a5ffc258fcfdb#diff-30e8e6dd0406833f9df53cdb848a31402e31aa4f48cae702ae39b41355e157acL374

I've made that change.  Please see if this is finally right.  Unfortunately it will break the possibility of the library being able to decode the command stream, but I don't think that will ever be a problem in real world usage.
Its also quite an ugly fix - if it works I'll see if I can make it more elegant.

**Comment by CatalyticMusa** [comment]
**Request Sent:**

```
g = GroupDepartmentKey(
        service_provider_id="Fake Telecommunications",
        group_id="AJTST",
        name="HQ",    
)
resp = api.command(
    "UserAddRequest14", 
    service_provider_id="Fake Telecommunications", 
    group_id="AJTST", 
    user_id="fakeuser@sip.faketelecommunications.com", 
    password="goodflavor!1",
    first_name="Fake", 
    last_name="User",
    calling_line_id_first_name="Fake",
    calling_line_id_last_name="User",
    email_address="Fakeuser@fakeemail.com",
    phone_number="27871231234",
    department=g,
    extension="1234",
)
```

**Response Received:**

```
Traceback (most recent call last):
  File "/Users/Musa/Desktop/2022 Projects/Python/ocip-testing/test.py", line 20, in <module>
    resp = api.command(
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/api.py", line 370, in command
    return self.receive_response()
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/api.py", line 259, in receive_response
    return self.decode_xml(content)
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/api.py", line 289, in decode_xml
    result.post_xml_decode_()
  File "/Users/Musa/Library/Caches/pypoetry/virtualenvs/ocip-testing-2kngksip-py3.9/lib/python3.9/site-packages/broadworks_ocip/base.py", line 609, in post_xml_decode_
    raise OCIErrorResponse(
broadworks_ocip.exceptions.OCIErrorResponse: OCIErrorResponse(None: [Error 6004] OCI XML Request validation error - Expected elements 'department language timeZone alias accessDeviceEndpoint trunkGroupDeviceEndpoint title pagerPhoneNumber mobilePhoneNumber emailAddress yahooId addressLocation address' instead of 'serviceProviderId' here in element command
<serviceProviderId xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">Fake Telecommunications</serviceProviderId>

Expected elements 'department language timeZone alias accessDeviceEndpoint trunkGroupDeviceEndpoint title pagerPhoneNumber mobilePhoneNumber emailAddress yahooId addressLocation address' instead of 'groupId' here in element command
<groupId xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">AJTST</groupId>

Expected elements 'department language timeZone alias accessDeviceEndpoint trunkGroupDeviceEndpoint title pagerPhoneNumber mobilePhoneNumber emailAddress yahooId addressLocation address' instead of 'name' here in element command
<name xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">HQ</name>
```

**Comment by nigelm** [comment]
Have been sent some sample XML and appear to have this working and testable now.

A release is just building - should be `2.0.4` which handles this.  For a couple of small samples of usage have a look at the last couple of tests in https://github.com/nigelm/broadworks_ocip/blob/master/tests/test_basic_command_xml.py#L357-L418
